from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/create/', views.project_create, name='project_create'),
    path('projects/<int:pk>/', views.project_detail, name='project_detail'),
    path('projects/<int:pk>/delete/', views.project_delete, name='project_delete'),
    path('projects/<int:pk>/edit/', views.project_edit, name='project_edit'),
    path('projects/<int:project_pk>/tasks/create/', views.task_create, name='task_create'),
    path('tasks/<int:pk>/delete/', views.task_delete, name='task_delete'),
    path('tasks/<int:pk>/edit/', views.task_edit, name='task_edit'),
    path('tasks/quick-add/', views.quick_add, name='quick_add'),
    path('report/', views.report, name='report'),
    path('chat/', views.chat_list, name='chat_list'),
    path('chat/open/<int:user_id>/', views.chat_open, name='chat_open'),
    path('chat/<int:conv_id>/', views.chat_room, name='chat_room'),
    path('chat/<int:conv_id>/send/', views.chat_send, name='chat_send'),
    path('chat/<int:conv_id>/poll/', views.chat_poll, name='chat_poll'),
    path('chat/unread/', views.chat_unread, name='chat_unread'),
    path('chat/msg/<int:msg_id>/edit/', views.chat_edit, name='chat_edit'),
    path('chat/msg/<int:msg_id>/delete/', views.chat_delete, name='chat_delete'),
    path('invite/create/', views.invite_create, name='invite_create'),
    path('invite/<str:token>/', views.invite_landing, name='invite_landing'),
    path('invite/', views.invite_list, name='invite_list'),
    path('analytics/', views.analytics, name='analytics'),
    path('projects/', views.projects_list, name='projects_list'),
    path('profile/', views.profile, name='profile'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/user/<int:user_id>/', views.admin_user_detail, name='admin_user_detail'),
]
