# Generated by Django 6.0.3 on 2026-03-17 08:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Затраченное время (ч)'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Запланировано'), ('in_progress', 'В работе'), ('done', 'Выполнено'), ('deferred', 'Отложено')], default='done', max_length=20, verbose_name='Статус'),
        ),
    ]
