# Generated by Django 6.0.3 on 2026-03-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет аватара'),
        ),
    ]
